export type PlayerType = {
  id: number;
  index: number;
  name: string;
  age: number;
  rate: number;
  position: "GK" | "CB" | "RB" | "LB" | "DM" | "CM" | "LW" | "RW" | "CF";
  img: string;
  color: "default" | "primary" | "secondary" | "success" | "warning" | "danger";
  shirtNumber: number;
};

// {
//   "formation": "4-3-3",
//   "lineup": {
//     "GK": 1,
//     "LB": 4,
//     "CB1": 5,
//     "CB2": 6,
//     "RB": 7,
//     "DM": 8,
//     "CM1": 9,
//     "CM2": 10,
//     "LW": 11,
//     "CF": 12,
//     "RW": 13
//   }
// }

export const marsei_players: PlayerType[] = [
  {
    id: 1,
    index: 1,
    name: "Lloris",
    age: 30,
    rate: 96,
    position: "GK",
    img: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Lloris_2018_%28cropped%29.jpg",
    color: "warning",
    shirtNumber: 1,
  },
  {
    id: 2,
    index: 2,
    name: "Oblak",
    age: 28,
    rate: 90,
    position: "GK",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn_G1OTYNuaZaOouzpYeD2ZMPO5n1Q0GQsqQ&s",
    color: "warning",
    shirtNumber: 1,
  },
  {
    id: 3,
    index: 3,
    name: "Sane",
    age: 30,
    rate: 88,
    position: "CB",
    img: "https://storage.schalke04.de/2019/06/190529_sane_senegal-1440x810.jpg",
    color: "primary",
    shirtNumber: 12,
  },

  {
    id: 4,
    index: 4,
    name: "Modric",
    age: 32,
    rate: 96,
    position: "CM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgHwnndwjEpe5b7iv1Vl8ip2bXAgEmHhg1hA&s",
    color: "success",
    shirtNumber: 6,
  },
  {
    id: 5,
    index: 5,
    name: "Gundogan",
    age: 30,
    rate: 94,
    position: "CM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGJ2FKRmnyhaEoa20IYePYliKQs14xTCSMS0WE8bl61oO993Nd4nCvUv2T5AQvwCHq8nTesKme_yjMK9RjxeO0QvxzJkscsn1pqEJlg711wzTnJQ&s&ec=121644689",
    color: "success",
    shirtNumber: 8,
  },
  {
    id: 6,
    index: 6,
    name: "Kroos",
    age: 26,
    rate: 92,
    position: "CM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-Sp7T6PfBN_vzxxtWKX5VS77y3eVSiwV-WA&s",
    color: "success",
    shirtNumber: 18,
  },
  {
    id: 7,
    index: 7,
    name: "Kante",
    age: 28,
    rate: 95,
    position: "CM",
    img: "https://res.cloudinary.com/chelsea-production/image/upload/c_fit,h_630,w_1200/v1/editorial/news/2021/06/14/kante-france-stock-2021",
    color: "success",
    shirtNumber: 14,
  },
  {
    id: 8,
    index: 8,
    name: "Dede",
    age: 29,
    rate: 90,
    position: "CB",
    img: "https://icdn.thelaziali.com/wp-content/uploads/2018/06/Dede.jpg",
    color: "primary",
    shirtNumber: 20,
  },
  {
    id: 9,
    index: 9,
    name: "Bale",
    age: 31,
    rate: 94,
    position: "LW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwruCBARrEvfFNFw57MIdKevJW6GLUmarmFg&s",
    color: "danger",
    shirtNumber: 11,
  },
  {
    id: 10,
    index: 10,
    name: "Ronaldo",
    age: 29,
    rate: 97,
    position: "CF",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_I7wepKjSmrN10TAAtBFCP9zJPYtBgEFqMQ&s",
    color: "danger",
    shirtNumber: 7,
  },
  {
    id: 11,
    index: 11,
    name: "Neymar",
    age: 28,
    rate: 95,
    position: "LW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLDjsqyD1OlzpKq7cwdkix_xxhVzyCyHsNgg&s",
    color: "danger",
    shirtNumber: 21,
  },
  {
    id: 12,
    index: 12,
    name: "Hazard",
    age: 29,
    rate: 91,
    position: "LW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVxGXf8jOjGRUs4ZRyo-m8OtFnwg1MljqdzQLq917wHtCN5vXWelk0PbrnzoXHyUweR40The2szUT9zyZXwmyw9Q",
    color: "danger",
    shirtNumber: 19,
  },
  {
    id: 13,
    index: 13,
    name: "Ibrahimovic",
    age: 32,
    rate: 94,
    position: "CF",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQtUMZQez-SnE3ThUbNt0RZp3gTvF1uxchLDnGURIGUOBY2dSrkoEpHFeRSQW4-QGpAr5JiTsORE1hY8JbNZ6WwPg",
    color: "danger",
    shirtNumber: 9,
  },
  {
    id: 14,
    index: 14,
    name: "Messi",
    age: 30,
    rate: 95,
    position: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQJ2sZUUc6xap9g__-HYUVi9LA2MnfG8_7xF33YejfCkudFpb2voAVKP3K2kg9RBHVo4gFx5saiDaNNzxhhMLjPg",
    color: "danger",
    shirtNumber: 10,
  },
  {
    id: 15,
    index: 15,
    name: "Alaba",
    age: 29,
    rate: 92,
    position: "LB",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHqwYsSJF4coFAuh7ckawclNlVAbiqI02FTa5l_6I2Ex4q1EAC0L3AwHBuJ9s90fdY_GbSt690wFXKo8j9eTwp5Q3VbpNhkrG8GNUtm3YGijyRYQ&s=10&ec=121644689",
    color: "primary",
    shirtNumber: 4,
  },
  {
    id: 16,
    index: 16,
    name: "Fernandinho",
    age: 29,
    rate: 91,
    position: "DM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbJkaTIOmqTD0HcsK0ohsNTHNV_65B8GIGEA&s",
    color: "success",
    shirtNumber: 15,
  },
  {
    id: 17,
    index: 17,
    name: "Robertson",
    age: 26,
    rate: 91,
    position: "LB",
    img: "https://i.guim.co.uk/img/media/f62f426b79aceb530b5ae2812d826688610049a2/1466_62_2518_1511/master/2518.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=4f6e6be802b9df69f813ce3f3d5cce71",
    color: "primary",
    shirtNumber: 26,
  },
  {
    id: 18,
    index: 18,
    name: "Van Dijk",
    age: 26,
    rate: 92,
    position: "CB",
    img: "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTiFyIWSWkRN4TqZQVvSTsWFTuKLRfqLW-ZllmL88EuaV6PqgQVHSSkRreeC-085mYPQc54IyMNHCTZN_U",
    color: "primary",
    shirtNumber: 3,
  },
  {
    id: 19,
    index: 19,
    name: "Koulibaly",
    age: 27,
    rate: 95,
    position: "CB",
    img: "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcS_V9bxquw2S0lbBwUqTe_QIBiyT_16VjrCBC64wCn4PgpLycwKCw--K5CgrZ_lEkf9Rwj_xnV3ZDXYHgM",
    color: "primary",
    shirtNumber: 5,
  },
  {
    id: 20,
    index: 20,
    name: "Walker",
    age: 25,
    rate: 92,
    position: "RB",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQd1XyPGH-EJuFth37UVex6K81AUmua1SCGpc4HmvSKRBg3BL63ZXszIAMzDIG-82Po6ob5F9AxPfMidoR8f1Eoxvr7sU7bm-xGLQVgpbo",
    color: "primary",
    shirtNumber: 2,
  },
  {
    id: 21,
    index: 21,
    name: "Cavajal",
    age: 23,
    rate: 86,
    position: "RB",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8AJq2UgURWuwqmJk8NuarCI-4jV45o8ELjA&s",
    color: "primary",
    shirtNumber: 27,
  },
  {
    id: 22,
    index: 22,
    name: "Gnapry",
    age: 28,
    rate: 91,
    position: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9FZaEO7ICFfAcEXQeHXW9dxU0wVCk31e70w&s",
    color: "danger",
    shirtNumber: 17,
  },
  {
    id: 23,
    index: 23,
    name: "Matinez",
    age: 29,
    rate: 90,
    position: "DM",
    img: "https://cdn.vox-cdn.com/thumbor/wJMmCsHOGLt7kCw5-Baep3_sCS8=/0x0:4851x3234/1200x800/filters:focal(2200x1037:2976x1813)/cdn.vox-cdn.com/uploads/chorus_image/image/68469485/1289586641.0.jpg",
    color: "success",
    shirtNumber: 16,
  },
  {
    id: 24,
    index: 24,
    name: "Shaw",
    age: 27,
    rate: 86,
    position: "LB",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVQuO0IEHQm__i7xqUzEZSKjBed1duJttBwQ&s",
    color: "primary",
    shirtNumber: 23,
  },
];
