import { nanoid } from "nanoid";

export type PlayerType = {
  id: string;
  index: number;
  name: string;
  age: number;
  rate: number;
  position:
    | "GK"
    | "CB"
    | "RB"
    | "RM"
    | "LB"
    | "LM"
    | "DM"
    | "CM"
    | "AM"
    | "LW"
    | "RW"
    | "CF"
    | "ST"
    | "Bench";
  img?: string;
  color: "default" | "primary" | "secondary" | "success" | "warning" | "danger";
  shirtNumber: number;
};

export const marsei_players: PlayerType[] = [
  {
    id: nanoid(),
    index: 1,
    name: "Armani",
    age: 32,
    rate: 91,
    position: "GK",
    img: "https://www.shutterstock.com/editorial/image-editorial/O1T7g7w0M8DeY1w3NDM0Nw==/argentina-goalkeeper-franco-armani-on-his-debut-440nw-9727998x.jpg",
    color: "warning",
    shirtNumber: 1,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Sánchez",
    age: 32,
    rate: 81,
    position: "GK",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBg7ksFZeYuKqrFI_E0TIxb_CHGbseBtH_H-fFZt2mH0ErA1ENHeMgiO8y7aE51l9P5m3l7IKuNScHFfn4cj-MRBXxrRD2hkRhKhbqA4SP&s=10",
    color: "warning",
    shirtNumber: 12,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Saliba",
    age: 26,
    rate: 82,
    position: "CB",
    img: "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcT_IGrTedLD05BulnWD7ny1Y88O9mWJtvhz71g_zB62hb3Ku157vIbQcafJNiqcGPrQ8DJ9MbWetwg3XZw",
    color: "primary",
    shirtNumber: 17,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Rabiot",
    age: 25,
    rate: 91,
    position: "CM",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Lens_-_Marseille_%2803-02-2021%29_12_%28cropped%29.jpg",
    color: "success",
    shirtNumber: 14,
  },
  {
    id: nanoid(),
    index: 1,
    name: "De bruyne",
    age: 23,
    rate: 94,
    position: "CM",
    img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRGX8U8kdM0ij313OQR-icOTIhZ3ZalGzGSDKRWgieFF3AR8riTysUFeLCAVLstT4p7-2r3Lau4U_2IqYcLx3I0FF5RDA6PqkYz2Eod6fIsLyTuOat3uAAiq8pJKbIp0qb9gWT6rkDaBZD3K6I2-_8J&s=19&ec=121644689",
    color: "success",
    shirtNumber: 6,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Ndombelle",
    age: 20,
    rate: 83,
    position: "CM",
    img: "https://m.media-amazon.com/images/M/MV5BNzg4NThiNWItMGQwOS00MjRmLWExODEtZGI4OGViYzc1MzUyXkEyXkFqcGc@._V1_.jpg",
    color: "success",
    shirtNumber: 22,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Aouar",
    age: 27,
    rate: 91,
    position: "CF",
    img: "https://assets.goal.com/images/v3/blt3dc47dca6e7deb1a/GOAL_-_Blank_WEB_-_Facebook_(9).png?auto=webp&format=pjpg&width=3840&quality=60",
    color: "danger",
    shirtNumber: 10,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Hernández",
    age: 27,
    rate: 94,
    position: "CB",
    img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQQfNZQcu_wV2yZrC3pfjTymQVUGlq4zRZQkcyDzRor_h3Eb481kVjCICZxk8WVgMo228wAoz6vpAaIxJyplhpd8Zm0TZxND2HXINcKOXzL7OSN_CAHeSQLSVuLOfkKHgLRNweH5dKXInk&s=19",
    color: "primary",
    shirtNumber: 4,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Son",
    age: 23,
    rate: 95,
    position: "CF",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMXsgC88bFM5O10BJBcmCsjidr9sf-skdIHQ&s",
    color: "danger",
    shirtNumber: 7,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Reus",
    age: 26,
    rate: 96,
    position: "CF",
    img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQv9Wxd1PpevdoNjaOMQemar2yJeBMSshGqKBLnfFkwO1cxIAM33-XG3g4X4N4D5h65lMMMqT8Q6s0k3LXWVreyIZGcli76rrAVuefXlqCo0ka34HDIhsXD-xwKvdRkV6LA3-trQLsQI7A&s=19",
    color: "danger",
    shirtNumber: 11,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Müller",
    age: 31,
    rate: 91,
    position: "CF",
    img: "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQclP0p4pQhH7g2oHQ_oPKgtAvX_ua27IUld1CZxbaGJgaqh9ZF0jMLo42lOcVnp-aH1e-KfvpHM4q5-AQ",
    color: "danger",
    shirtNumber: 13,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Rashford",
    age: 21,
    rate: 87,
    position: "CF",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvRbfBqEyCxBSDRZbskP-TGFCXmcSYJEQ3DA&s",
    color: "danger",
    shirtNumber: 9,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Ward-Prowse",
    age: 23,
    rate: 91,
    position: "RM",
    img: "https://assets.dfb.de/uploads/000/205/110/custom_style_1_Daniel-Caligiuri.jpg?1564681783",
    color: "success",
    shirtNumber: 8,
  },
  {
    id: nanoid(),
    index: 2,
    name: "#",
    age: 27,
    rate: 82,
    position: "CB",
    img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRRawXIQyW84sXVTZp1W5JUlKkNhivoK9okLYd5A-p6QzyVv80y3Hb8J7KzQlDxGbibgFakQ2JG-Nbz017s0f-Xjh4cKut6CZ_NqUKe5gpiMxK8M3TH-mVDC2POBLFoXxZJgm24DoFjHH1m&s=19",
    color: "primary",
    shirtNumber: 23,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Zobnin",
    age: 21,
    rate: 81,
    position: "CM",
    img: "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRdeezFGgnqqCWcghvTignvha6QH7xCOXqLeAYs79oL6WOldLDaJjxrMlqqPtio0dIwF0f19qffGZWjUf8",
    color: "success",
    shirtNumber: 39,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Upamecano",
    age: 20,
    rate: 80,
    position: "CB",
    img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRXWmEo1fpY_d-SvBF55o7YNT-pedrs8bhvO9pigZQh3UHFqRcgz6J75770imdqsUeX3p3SVyRxfY-SX84HTm-1iW_yitFTdIRko3ThWh6YF2_gkWGq1iVxXa2gLtk7eaO9J-s5Y99SICE7Zp5yw9Q&s=19&ec=121644689",
    color: "primary",
    shirtNumber: 20,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Chiellini",
    age: 25,
    rate: 93,
    position: "CB",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnHvfnRzk41LfY8986-cgBDEpoaPEpxQkl2w&s",
    color: "primary",
    shirtNumber: 5,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Bonucci",
    age: 30,
    rate: 94,
    position: "CB",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnHvfnRzk41LfY8986-cgBDEpoaPEpxQkl2w&s",
    color: "primary",
    shirtNumber: 19,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Tierney",
    age: 22,
    rate: 83,
    position: "LM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVcI5BZWt4JLAlYqLIkrfm31L1-jd0dSytvduO0BoCLee6eSDZP9klhF5sKRhczip0DWyYpU_fH5OSALwwwrIcqqDa10rnoji_5XomZQ5E&s=10",
    color: "success",
    shirtNumber: 33,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Cancelo",
    age: 25,
    rate: 94,
    position: "RM",
    img: "https://res.cloudinary.com/chelsea-production/image/upload/c_fit,h_630,w_1200/v1/editorial/news/2023/07/06/azpilicueta-farewell-top",
    color: "success",
    shirtNumber: 2,
  },
  {
    id: nanoid(),
    index: 2,
    name: "Džeko",
    age: 27,
    rate: 94,
    position: "CF",
    img: "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcR8nWCyjLrqcpS2aDbJhYcXfdd9WykOazc9bBYR94HuNUpxCpF83lv_aBt5rbbhtH0f-X3zMr9FjVxULHc",
    color: "danger",
    shirtNumber: 26,
  },
  {
    id: nanoid(),
    index: 1,
    name: "Cucurella",
    age: 26,
    rate: 88,
    position: "LM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiJ4OexhN27xVWZXjzAkqLe45b_T8YSpvys5jhp8H5iqL8L7-WiobZ9mk6J6IgzSx8zH_XWSsCMPCs1fquKz2MEp6HEM2hhQ5b7_vwHARCzv-eFA&s=10&ec=121644689",
    color: "success",
    shirtNumber: 3,
  },
];
