export type PlayerType = {
  id: number;
  index: number;
  name: string;
  age: number;
  rate: number;
  positiom: "GK" | "CB" | "RB" | "LB" | "DM" | "CM" | "LW" | "RW" | "CF";
  img: string;
  color: "default" | "primary" | "secondary" | "success" | "warning" | "danger";
  shirtNumber: number;
};

export const players: PlayerType[] = [
  {
    id: 1,
    index: 2,
    name: "Lloris",
    age: 27,
    rate: 95,
    positiom: "GK",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3687_by_Stepro_%28cropped%29.jpg/170px-2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3687_by_Stepro_%28cropped%29.jpg",
    color: "warning",
    shirtNumber: 1,
  },
  {
    id: 2,
    index: 5,
    name: "Alves",
    age: 31,
    rate: 92,
    positiom: "RB",
    img: "https://e0.365dm.com/14/10/1600x900/dani-alves-barcelona-defender_3217985.jpg?20141018083011",
    color: "primary",
    shirtNumber: 2,
  },
  {
    id: 3,
    index: 6,
    name: "Sane",
    age: 27,
    rate: 90,
    positiom: "CB",
    img: "https://storage.schalke04.de/2019/06/190529_sane_senegal-1440x810.jpg",
    color: "primary",
    shirtNumber: 12,
  },
  {
    id: 4,
    index: 8,
    name: "Dede",
    age: 26,
    rate: 90,
    positiom: "CB",
    img: "https://icdn.thelaziali.com/wp-content/uploads/2018/06/Dede.jpg",
    color: "primary",
    shirtNumber: 20,
  },
  {
    id: 5,
    index: 9,
    name: "Alaba",
    age: 26,
    rate: 92,
    positiom: "LB",
    img: "https://b3504934.smushcdn.com/3504934/wp-content/uploads/2023/11/David-Alaba-VPH-P.jpg?lossy=2&strip=1&webp=1",
    color: "primary",
    shirtNumber: 4,
  },
  {
    id: 6,
    index: 17,
    name: "Fernandinho",
    age: 26,
    rate: 91,
    positiom: "DM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbJkaTIOmqTD0HcsK0ohsNTHNV_65B8GIGEA&s",
    color: "success",
    shirtNumber: 15,
  },
  {
    id: 7,
    index: 16,
    name: "Kante",
    age: 25,
    rate: 94,
    positiom: "CM",
    img: "https://res.cloudinary.com/chelsea-production/image/upload/c_fit,h_630,w_1200/v1/editorial/news/2021/06/14/kante-france-stock-2021",
    color: "success",
    shirtNumber: 14,
  },
  {
    id: 8,
    index: 18,
    name: "Modric",
    age: 29,
    rate: 96,
    positiom: "CM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgHwnndwjEpe5b7iv1Vl8ip2bXAgEmHhg1hA&s",
    color: "success",
    shirtNumber: 6,
  },
  {
    id: 9,
    index: 20,
    name: "Bale",
    age: 28,
    rate: 94,
    positiom: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwruCBARrEvfFNFw57MIdKevJW6GLUmarmFg&s",
    color: "danger",
    shirtNumber: 11,
  },
  {
    id: 10,
    index: 22,
    name: "Ronaldo",
    age: 26,
    rate: 98,
    positiom: "CF",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmtXFylAyzycvCkVPkuvQKLLccYtWfcaT4ng&s",
    color: "danger",
    shirtNumber: 7,
  },
  {
    id: 11,
    index: 24,
    name: "Neymar",
    age: 25,
    rate: 95,
    positiom: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLDjsqyD1OlzpKq7cwdkix_xxhVzyCyHsNgg&s",
    color: "danger",
    shirtNumber: 21,
  },
  {
    id: 12,
    index: 26,
    name: "Neymar",
    age: 25,
    rate: 95,
    positiom: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLDjsqyD1OlzpKq7cwdkix_xxhVzyCyHsNgg&s",
    color: "danger",
    shirtNumber: 21,
  },
  {
    id: 13,
    index: 27,
    name: "Ronaldo",
    age: 26,
    rate: 98,
    positiom: "CF",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmtXFylAyzycvCkVPkuvQKLLccYtWfcaT4ng&s",
    color: "danger",
    shirtNumber: 7,
  },
  {
    id: 14,
    index: 28,
    name: "Bale",
    age: 28,
    rate: 94,
    positiom: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwruCBARrEvfFNFw57MIdKevJW6GLUmarmFg&s",
    color: "danger",
    shirtNumber: 11,
  },
  {
    id: 15,
    index: 31,
    name: "Modric",
    age: 29,
    rate: 96,
    positiom: "CM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgHwnndwjEpe5b7iv1Vl8ip2bXAgEmHhg1hA&s",
    color: "success",
    shirtNumber: 6,
  },
  {
    id: 16,
    index: 33,
    name: "Kante",
    age: 25,
    rate: 94,
    positiom: "CM",
    img: "https://res.cloudinary.com/chelsea-production/image/upload/c_fit,h_630,w_1200/v1/editorial/news/2021/06/14/kante-france-stock-2021",
    color: "success",
    shirtNumber: 14,
  },
  {
    id: 17,
    index: 32,
    name: "Fernandinho",
    age: 26,
    rate: 91,
    positiom: "DM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbJkaTIOmqTD0HcsK0ohsNTHNV_65B8GIGEA&s",
    color: "success",
    shirtNumber: 15,
  },
  {
    id: 18,
    index: 40,
    name: "Alaba",
    age: 26,
    rate: 92,
    positiom: "LB",
    img: "https://b3504934.smushcdn.com/3504934/wp-content/uploads/2023/11/David-Alaba-VPH-P.jpg?lossy=2&strip=1&webp=1",
    color: "primary",
    shirtNumber: 4,
  },
  {
    id: 19,
    index: 41,
    name: "Dede",
    age: 26,
    rate: 90,
    positiom: "CB",
    img: "https://icdn.thelaziali.com/wp-content/uploads/2018/06/Dede.jpg",
    color: "primary",
    shirtNumber: 20,
  },
  {
    id: 20,
    index: 43,
    name: "Sane",
    age: 27,
    rate: 90,
    positiom: "CB",
    img: "https://storage.schalke04.de/2019/06/190529_sane_senegal-1440x810.jpg",
    color: "primary",
    shirtNumber: 12,
  },

  {
    id: 21,
    index: 44,
    name: "Alves",
    age: 31,
    rate: 92,
    positiom: "RB",
    img: "https://e0.365dm.com/14/10/1600x900/dani-alves-barcelona-defender_3217985.jpg?20141018083011",
    color: "primary",
    shirtNumber: 2,
  },
  {
    id: 22,
    index: 47,
    name: "Lloris",
    age: 27,
    rate: 95,
    positiom: "GK",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3687_by_Stepro_%28cropped%29.jpg/170px-2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3687_by_Stepro_%28cropped%29.jpg",
    color: "warning",
    shirtNumber: 1,
  },
];
