export type PlayerType = {
  id: number;
  index: number;
  name: string;
  age: number;
  rate: number;
  positiom: "GK" | "CB" | "RB" | "LB" | "DM" | "CM" | "LW" | "RW" | "CF";
  img: string;
  color: "default" | "primary" | "secondary" | "success" | "warning" | "danger";
  shirtNumber: number;
};

export const players: PlayerType[] = [
  {
    id: 1,
    index: 2,
    name: "Lloris",
    age: 27,
    rate: 95,
    positiom: "GK",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3687_by_Stepro_%28cropped%29.jpg/170px-2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3687_by_Stepro_%28cropped%29.jpg",
    color: "warning",
    shirtNumber: 1,
  },
  {
    id: 2,
    index: 5,
    name: "Alves",
    age: 31,
    rate: 92,
    positiom: "RB",
    img: "https://e0.365dm.com/14/10/1600x900/dani-alves-barcelona-defender_3217985.jpg?20141018083011",
    color: "primary",
    shirtNumber: 2,
  },
  {
    id: 3,
    index: 6,
    name: "Sane",
    age: 27,
    rate: 90,
    positiom: "CB",
    img: "https://storage.schalke04.de/2019/06/190529_sane_senegal-1440x810.jpg",
    color: "primary",
    shirtNumber: 12,
  },
  {
    id: 4,
    index: 8,
    name: "Dede",
    age: 26,
    rate: 90,
    positiom: "CB",
    img: "https://icdn.thelaziali.com/wp-content/uploads/2018/06/Dede.jpg",
    color: "primary",
    shirtNumber: 20,
  },
  {
    id: 5,
    index: 9,
    name: "Alaba",
    age: 26,
    rate: 92,
    positiom: "LB",
    img: "https://b3504934.smushcdn.com/3504934/wp-content/uploads/2023/11/David-Alaba-VPH-P.jpg?lossy=2&strip=1&webp=1",
    color: "primary",
    shirtNumber: 4,
  },
  {
    id: 6,
    index: 17,
    name: "Fernandinho",
    age: 26,
    rate: 91,
    positiom: "DM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbJkaTIOmqTD0HcsK0ohsNTHNV_65B8GIGEA&s",
    color: "success",
    shirtNumber: 15,
  },
  {
    id: 7,
    index: 16,
    name: "Kante",
    age: 25,
    rate: 94,
    positiom: "CM",
    img: "https://res.cloudinary.com/chelsea-production/image/upload/c_fit,h_630,w_1200/v1/editorial/news/2021/06/14/kante-france-stock-2021",
    color: "success",
    shirtNumber: 14,
  },
  {
    id: 8,
    index: 18,
    name: "Modric",
    age: 29,
    rate: 96,
    positiom: "CM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgHwnndwjEpe5b7iv1Vl8ip2bXAgEmHhg1hA&s",
    color: "success",
    shirtNumber: 6,
  },
  {
    id: 9,
    index: 20,
    name: "Bale",
    age: 28,
    rate: 94,
    positiom: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwruCBARrEvfFNFw57MIdKevJW6GLUmarmFg&s",
    color: "danger",
    shirtNumber: 11,
  },
  {
    id: 10,
    index: 22,
    name: "Ronaldo",
    age: 26,
    rate: 98,
    positiom: "CF",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmtXFylAyzycvCkVPkuvQKLLccYtWfcaT4ng&s",
    color: "danger",
    shirtNumber: 7,
  },
  {
    id: 11,
    index: 24,
    name: "Neymar",
    age: 25,
    rate: 95,
    positiom: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLDjsqyD1OlzpKq7cwdkix_xxhVzyCyHsNgg&s",
    color: "danger",
    shirtNumber: 21,
  },
  {
    id: 12,
    index: 26,
    name: "Hazard",
    age: 26,
    rate: 91,
    positiom: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVxGXf8jOjGRUs4ZRyo-m8OtFnwg1MljqdzQLq917wHtCN5vXWelk0PbrnzoXHyUweR40The2szUT9zyZXwmyw9Q",
    color: "danger",
    shirtNumber: 19,
  },
  {
    id: 13,
    index: 27,
    name: "Ibrahimovic",
    age: 26,
    rate: 95,
    positiom: "CF",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQtUMZQez-SnE3ThUbNt0RZp3gTvF1uxchLDnGURIGUOBY2dSrkoEpHFeRSQW4-QGpAr5JiTsORE1hY8JbNZ6WwPg",
    color: "danger",
    shirtNumber: 9,
  },
  {
    id: 14,
    index: 28,
    name: "Messi",
    age: 27,
    rate: 96,
    positiom: "RW",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQJ2sZUUc6xap9g__-HYUVi9LA2MnfG8_7xF33YejfCkudFpb2voAVKP3K2kg9RBHVo4gFx5saiDaNNzxhhMLjPg",
    color: "danger",
    shirtNumber: 10,
  },
  {
    id: 15,
    index: 31,
    name: "Gundogan",
    age: 27,
    rate: 94,
    positiom: "CM",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/20180602_FIFA_Friendly_Match_Austria_vs._Germany_%C4%B0lkay_G%C3%BCndo%C4%9Fan_850_0728.jpg/440px-20180602_FIFA_Friendly_Match_Austria_vs._Germany_%C4%B0lkay_G%C3%BCndo%C4%9Fan_850_0728.jpg",
    color: "success",
    shirtNumber: 8,
  },
  {
    id: 16,
    index: 33,
    name: "Joaquin",
    age: 31,
    rate: 94,
    positiom: "CM",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Joaquin_2022_%28cropped%29.jpg/440px-Joaquin_2022_%28cropped%29.jpg",
    color: "success",
    shirtNumber: 17,
  },
  {
    id: 17,
    index: 32,
    name: "Martinez",
    age: 26,
    rate: 90,
    positiom: "DM",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSit39UwH-b2kuqvwuCgFyelXR65rTn6vVjIPjsMNrz06aSZGaavRDPgC_5WrH-gtSGnGjsFZ376etYDiSv2oKJ6ohs4cjaqbqt1giXIsg",
    color: "success",
    shirtNumber: 16,
  },
  {
    id: 18,
    index: 40,
    name: "Young",
    age: 29,
    rate: 90,
    positiom: "LB",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMEINzCr_XfJm0-NQ5Hm7cJ7yBw-6bRkLwmg&s",
    color: "primary",
    shirtNumber: 18,
  },
  {
    id: 19,
    index: 41,
    name: "Van Dijk",
    age: 23,
    rate: 90,
    positiom: "CB",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXqa4iQLOuDpUB5l2_oD61nNxbvdHR_dmNQQ&s",
    color: "primary",
    shirtNumber: 3,
  },
  {
    id: 20,
    index: 43,
    name: "Boateng",
    age: 28,
    rate: 88,
    positiom: "CB",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyxWGaAdX78E7E5IlUDbrNksiw2tvsIqtIHw&s",
    color: "primary",
    shirtNumber: 5,
  },

  {
    id: 21,
    index: 44,
    name: "Walker",
    age: 22,
    rate: 88,
    positiom: "RB",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQd1XyPGH-EJuFth37UVex6K81AUmua1SCGpc4HmvSKRBg3BL63ZXszIAMzDIG-82Po6ob5F9AxPfMidoR8f1Eoxvr7sU7bm-xGLQVgpbo",
    color: "primary",
    shirtNumber: 22,
  },
  {
    id: 22,
    index: 47,
    name: "Fabianski",
    age: 29,
    rate: 92,
    positiom: "GK",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdUEXNAry-o_Tvnr0ikGqSjEnp9X56WUHmbw&s",
    color: "warning",
    shirtNumber: 13,
  },
];
